### ISSUE TITLE
syslog

### ISSUE THREAD

**Issue by birka1** [stamparm/maltrail#87]
hi
is there away to send the threat logs also to syslog (SIEM)?

**Comment by stamparm** [comment]
Currently not, but I would like to know the syslog format you (or other users) would like to support?

**Comment by xECK29x** [comment]
CEF (Common Event Format) would be best. It is one of the more common standards and is supported by almost all SIEMs or log aggregation tools including Splunk, ArcSight, LogRhythm and IBM QRadar.

http://www.iwebdev.it/blog/?tag=common-event-format
https://www.protect724.hpe.com/docs/DOC-1072

**Comment by birka1** [comment]
agree with xECK29x  

by the way there is newletter or something like that ? how we inform about new version or new features?

**Comment by jjjan** [comment]
we appreciate to have it as splunk app

**Comment by stamparm** [comment]
@xECK29x so, something like this would suffice?

```
Mar 16 16:43:10 sensor1 CEF:0|maltrail|sensor|0.10.115|2016-02-02|known attacker|10|src=10.0.0.192 spt=1234 dst=12.121.122.82 dpt=4123 proto=TCP
```

**Comment by xECK29x** [comment]
@stamparm That looks great!

**Comment by jjjan** [comment]
that's great with nice dashboard

**Comment by stamparm** [comment]
Basic implementation is done. Now you'll find inside the `maltrail.conf` the following NEW option:

```
# Remote address to send syslog entries
#SYSLOG_SERVER 192.168.2.107:514
```

Just uncomment it (`SYSLOG_SERVER`) and write your own SYSLOG server `address:port`.

Current known limitations is that `Severity` is put to `0` as the column `severity` inside the Maltrail's web client is calculating it inside (JS logic). If there will be a need to transfer that same "logic" I'll do it here too.

Also, I am not sure whether `trail` and `reference` columns are also needed inside the SYSLOG message.

**Comment by xECK29x** [comment]
This looks great! I would say it's safe to over-log items and include the trail and reference fields and let the user decide what to strip out or create extracted fields for in their system of use. Can't wait to use this with Splunk!

**Comment by stamparm** [comment]
@xECK29x with the latest revision both trail and reference are included too

**Comment by xECK29x** [comment]
Fantastic!

**Comment by birka1** [comment]
Great! works like a charm
thanks

**Comment by jjjan** [comment]
you are great. we need Severity too. do you make splunk app or dashboard for project?

**Comment by jjjan** [comment]
another things is important when user want to query log in SIEM it's better to have more detail on log for example Mar 16 16:43:10 sensor1 CEF:0|name=sensor|ver=0.10.115|time=2016-05-10|trail=known attacker|10|src=10.0.0.192 spt=1234 dst=12.121.122.82 dpt=4123 proto=TCP

**Comment by dpicollege** [comment]
first of all thanks for useful project. after so long time we need structure log like the user @jjjan  said or make splunk app. we need all output like severity. good luck

**Comment by dbinoj** [comment]
@stamparm, If you are implementing severity for syslog messages, please send that data via UDP_SERVER option too. If needed, it can be made configurable. Our SIEM is happy with the RAW log format as it is just CSV with space as delimiter and double quotes to include fields with spaces. Also this format requires less space as column names are fixed and not transported with each message.

**Comment by jjjan** [comment]
Hello, again
as i see at sensor output could you add some key for the value such as "malware" for exmaple we have some things like this  version=0.10.148|time=2017-07-12| threat=malware |0|src=93.174.95.106.
i have this request before in other post. but in latest version we have nothing for that. for example threat for malware.

**Comment by netsysadm** [comment]
Hi i tried commention the SYSLOG in maltrail conf and allow the port both on the maltrail server going to the syslog server(graylog) tried both CEF UDP and SYSLOG UDP but logserver still not able to receive anything, the port on the maltrail isnt even listening. Can anyone help please? Do i need to install rsyslog for this purpose?

**Comment by stamparm** [comment]
Done a long time ago - `SYSLOG_SERVER` in maltrail.conf sends events on as CEF/syslog (there's `LOGSTASH_SERVER` for JSON too).
